server:
  port: 9005
spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 10GB
  application:
    name: star-forum-soft
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_forum_soft?characterEncoding=utf-8

pagehelper:
  params: count=countSql
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl